// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingPlatformTest.Models;

namespace TradingPlatformTest.Migrations
{
    [DbContext(typeof(TradingPlatformContext))]
    [Migration("20200718184135_Rate-Add-Line")]
    partial class RateAddLine
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TradingPlatformTest.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TradingPlatformTest.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("TradingPlatformTest.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bolivarian Republic of Venezuela"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Caribbean"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 31,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 36,
                            Name = "France"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 46,
                            Name = "India"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Korea"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Lao P.D.R."
                        },
                        new
                        {
                            Id = 63,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Macao S.A.R."
                        },
                        new
                        {
                            Id = 70,
                            Name = "Macedonia (FYROM)"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 80,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 87,
                            Name = "China"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Principality of Monaco"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Serbia and Montenegro (Former)"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 106,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 119,
                            Name = "U.A.E."
                        },
                        new
                        {
                            Id = 120,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 121,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 122,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("TradingPlatformTest.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RateLastSyncTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("TradingPlatformTest.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMultiCountryPossible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsService")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId1");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("TradingPlatformTest.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TradingPlatformTest.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TradingPlatformTest.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TradingPlatformTest.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingPlatformTest.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TradingPlatformTest.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradingPlatformTest.Models.City", b =>
                {
                    b.HasOne("TradingPlatformTest.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("TradingPlatformTest.Models.Country", b =>
                {
                    b.HasOne("TradingPlatformTest.Models.Currency", "Currency")
                        .WithMany("Countries")
                        .HasForeignKey("CurrencyId");
                });

            modelBuilder.Entity("TradingPlatformTest.Models.Item", b =>
                {
                    b.HasOne("TradingPlatformTest.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId");

                    b.HasOne("TradingPlatformTest.Models.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("TradingPlatformTest.Models.Order", b =>
                {
                    b.HasOne("TradingPlatformTest.Models.Item", "Item")
                        .WithMany("Orders")
                        .HasForeignKey("ItemId");

                    b.HasOne("TradingPlatformTest.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("TradingPlatformTest.Models.User", b =>
                {
                    b.HasOne("TradingPlatformTest.Models.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId");
                });
#pragma warning restore 612, 618
        }
    }
}
